name: dos
channels:
  - conda-forge
  - defaults
dependencies:
  - ca-certificates=2024.8.30
  - ipykernel=6.29.5
  - ipython=8.30.0
  - jinja2=3.1.4
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - openssl=3.4.0
  - pip=24.2
  - python=3.12.7
  - setuptools=75.1.0
  - wheel=0.44.0
  - yaml=0.2.5
  - pip:
      - accelerate==1.1.1
      - diffusers==0.32.2
      - huggingface-hub==0.26.3
      - jupyterlab-widgets==3.0.13
      - matplotlib==3.10.0
      - numpy==2.1.3
      - open-clip-torch==2.30.0
      - opencv-python==4.10.0.84
      - pillow==11.0.0
      - scikit-learn==1.6.1
      - scipy==1.15.1
      - tokenizers==0.21.0
      - torch==2.5.1
      - torchvision==0.20.1
      - tqdm==4.67.1
      - transformers==4.48.2
      - gguf==0.14.0
      - protobuf==5.29.3
      - fairscale==0.4.4
      - ruamel.yaml==0.17.32
      - spacy==3.8.4
      - bitsandbytes==0.45.3
      - scikit-image==0.25.2
      - pytorch-metric-learning==2.5.0
