BACKGROUND = [
    "in a forest",
    "in a desert",
    "on a mountain",
    "on a beach",
    "in a grassland",
    "in the Arctic",
    "in the savanna",
    "on the ocean surface",
    "underwater",
    "in a river",
    "in a lake",
    "in a coral reef",
    "in a cave",
    "in a city street",
    "in a suburban neighborhood",
    "in a farm field",
    "at a construction site",
    "at a stadium",
    "in a parking lot",
    "on a road",
    "on a railway track",
    "on a boat deck",
    "on an airport runway",
    "in the sky",
    "in space",
    "in a living room",
    "in a kitchen",
    "in a bedroom",
    "in a bathroom",
    "in an office",
    "in a classroom",
    "in a laboratory",
    "in a factory",
    "in a warehouse",
    "in a shopping mall",
    "in a grocery store",
]

VISUAL_ATTRIBUTE = [
    "round",
    "oval",
    "square",
    "rectangular",
    "triangular",
    "spherical", 
    "cylindrical",
    "conical", 
    "flat",
    "elongated",
    "pointed",
    "curved",
    "ring-shaped",
    "disc-shaped"
    "irregular",
    "spiral",
    "star-shaped",
    "jagged",
    "boxy",
    "stocky",
    "smooth",
    "rough",
    "bumpy",
    "grainy",
    "granular",
    "fuzzy",
    "hairy",
    "woolly",
    "leathery",
    "scaly",
    "feathery",
    "slimy",
    "wrinkled",
    "shaggy",
    "shiny",
    "matte",
    "porous",
    "spongy",
    "striped",
    "spotted",
    "patterned",
    "rubbery",
]
